services:
  searxng:
    container_name: searxng
    build:
      dockerfile_inline: |
        FROM docker.io/searxng/searxng:latest
        RUN /usr/local/searxng/.venv/bin/python3 -m ensurepip && \
            /usr/local/searxng/.venv/bin/python3 -m pip install --no-cache-dir searxng-bm25-reranker && \
            /usr/local/searxng/.venv/bin/python3 -m pip uninstall -y pip
    restart: always
    ports:
      - "127.0.0.1:8888:8080"
    volumes:
      # Map your private local file to the standard path inside the container
      - ./searxng/settings.private.yml:/etc/searxng/settings.yml:rw
    env_file:
      - .env
    environment:
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
